### ISSUE TITLE
Color scheme not found

### ISSUE THREAD

**Issue by k0pernicus** [daoli/dotvim#1]
When installing your configuration file using `install.sh`, an error occured:
```
Error detected while processing /Users/xxxx/.vimrc:
line  218:
E185: Cannot find color scheme 'Tomorrow-Night-Eighties'
```
It seems that you need to explicit the download of this color scheme.

**Comment by daoli** [comment]
Strange... It's actually included in _vimrc, L39: ```Plugin 'flazz/vim-colorschemes'```

https://github.com/flazz/vim-colorschemes/blob/master/colors/Tomorrow-Night-Eighties.vim

Maybe you need to restart vim after ``./install.sh``?

**Comment by k0pernicus** [comment]
Hi,
it's being a long time so I will close it now... Sorry for the delay :)
